### ISSUE TITLE
Error compiling ResNet

### ISSUE THREAD

**Issue by mkskeller** [mpc-msri/EzPC#69]
I'm getting the following error after running the instructions in the ResNet readme and then `./CompileTF.sh -f Networks/ResNet/ResNet_main.py` in `Athos`:
```
Traceback (most recent call last):
  File "SeeDot.py", line 94, in <module>
    obj.runCompilerDriver()
  File "SeeDot.py", line 88, in runCompilerDriver
    obj.run()
  File "/home/marcel/EzPC/Athos/SeeDot/Compiler.py", line 124, in run
    GC.run([mtdAST])
  File "/home/marcel/EzPC/Athos/SeeDot/Optimizations/GarbageCollector.py", line 173, in run
    self.visit(self.ast, args)
  File "/home/marcel/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 114, in visit
    return self.visitLet(node, args)
  File "/home/marcel/EzPC/Athos/SeeDot/Optimizations/GarbageCollector.py", line 188, in visitLet
    self.visit(node.expr, args)
(...)
  File "/home/marcel/EzPC/Athos/SeeDot/Optimizations/GarbageCollector.py", line 188, in visitLet
    self.visit(node.expr, args)
  File "/home/marcel/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 114, in visit
    return self.visitLet(node, args)
  File "/home/marcel/EzPC/Athos/SeeDot/Optimizations/GarbageCollector.py", line 192, in visitLet
    assert False, " visit of {} not implemented in GarbageCollector pass".format(str(type(node.decl)))
AssertionError:  visit of <class 'AST.AST.FusedBatchNorm'> not implemented in GarbageCollector pass
```

**Comment by bhatuzdaname** [comment]
Fixed in 1a3b304c6da6a7686d51223f78810b19670ed833
Thank you for reporting! Let me know if you run into any further issues.
